server:
  port: 5000

spring:
  application:
    name: roim-olam-server

  datasource:
    platform: postgres
    url: jdbc:postgresql://roim-olam-pg.cbxt9i4cijlc.eu-central-1.rds.amazonaws.com:5430/roim_olam
    username: postgres
    password: 12345678
    driverClassName: org.postgresql.Driver
