server:
  port: 5000

spring:
  application:
    name: roim-olam-server
  profiles:
    active: '@spring.profiles.active@'

  jpa:
    database: ${DATABASE}
    show-sql: true
    hibernate:
      ddl-auto: ${DDL_STRATEGY}
    properties.hibernate.dialect: ${HIBERNATE_DIALECT}

  datasource:
    platform: ${SQL_PLATFORM}
    url: ${SQL_URL}
    username: ${SQL_USERNAME}
    password: ${SQL_PASSWORD}
    driverClassName: ${SQL_DRIVER}
