server:
  port: 5000

spring:
  application:
    name: roim-olam-server
#  profiles:
#    active: @spring.profiles.active@

  datasource:
    platform: postgres
    url: jdbc:postgresql://roim-olam-db.cbxt9i4cijlc.eu-central-1.rds.amazonaws.com:5432/roim_olam
    username: postgres
    password: 12345678
    driverClassName: org.postgresql.Driver
