server:
  port: 5000

spring:
  application:
    name: roim-olam-server
  profiles:
    active: @spring.profiles.active@

  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/roim_olam
    username: postgres
    password: ${SQL_PASSWORD}
    driverClassName: org.postgresql.Driver
